apiVersion: v1
kind: Service
metadata:
  name: leader-followers-app-service
spec:
  selector:
    app: app # All pods with the app=app label belong to this service
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
