apiVersion: apps/v1
kind: Deployment
metadata:
  name: leader-followers-app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: leader-followers-app
        image: igorkkolasa/kuberneteslearning:app
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /health/check
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness/check
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            cpu: 250m
            memory: 1G
          limits:
            cpu: 250m
            memory: 1G
        env:                               # Variables to access postgres database
          - name: DB_NAME
            value: mydb
          - name: DB_SERVER
            value: leader-followers-postgres-db-service
          - name: DB_PORT
            value: '5432'
          - name: DB_PASSWORD
            value: password
          - name: DB_USER
            value: postgres-user
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname  # Prefer to be on a different node to other event API pods
              labelSelector:
                matchLabels:
                  app: app