apiVersion: v1
kind: Service
metadata:
  name: leader-followers-postgres-db-service
spec:
  clusterIP: None # The StatefulSet's governing Service must be headless
  selector:
    app: postgres # All pods with the app=postgres label belong to this service
  ports:
    - port: 80
      targetPort: 5432